version: "3.8"
services:
  db:
    container_name: scelefeed-db
    image: postgres:13.3-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - scelefeed
    ports: 
      - "5433:5432"

  server:
    container_name: server-scelefeed
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mongo
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - scelefeed
    command: ["/app/main"]

volumes:
  db-data:
    driver: local
    
networks:
  scelefeed:
    driver: bridge
